version: '2'

services:
  
  devcontainer:
    build:
      context: .
      args:
        DBT_VERSION: 1.0.0
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/workspace
  
  clickhouse:
    image: clickhouse/clickhouse-server:22.3
    ports:
      - 9000:9000
      - 8123:8123

  metabase:
    image: metabase/metabase:v0.44.6
    volumes:
      - ./metabase/plugins:/plugins
      - ./metabase/metabase.db:/metabase.db/
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase.db
    ports: 
      - 3000:3000

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    env_file:
      - .env      
    volumes:
      - .:/cube/conf
