config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: True

mybi_dbt_showcase:
  target: prod

  outputs:
  
    prod:
      type: clickhouse
      host: clickhouse
      driver: native
      port: 9000
      user: default
      schema: analytics
      threads: 3
