config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: True

mybi_dbt_showcase:
  target: prod

  outputs:
  
    prod:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: default
      schema: analytics
      threads: 3
      custom_settings: { enable_positional_arguments: 1}
